-- MySQL Script generated by MySQL Workbench
-- 11/22/14 18:35:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema YuGiOh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YuGiOh` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `YuGiOh` ;

-- -----------------------------------------------------
-- Table `YuGiOh`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`User` (
  `UserName` VARCHAR(64) NOT NULL COMMENT '用户名',
  `Password` VARCHAR(64) NOT NULL COMMENT '密码',
  `Email` VARCHAR(500) NOT NULL COMMENT '电子邮件',
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '用户登录信息表';


-- -----------------------------------------------------
-- Table `YuGiOh`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`UserInfo` (
  `NickName` VARCHAR(64) NULL COMMENT '昵称',
  `Image` VARCHAR(500) NULL COMMENT '头像',
  `Sex` INT NULL COMMENT '性别',
  `Age` INT NULL COMMENT '年龄',
  `IC` CHAR(18) NULL COMMENT '身份证号码',
  `Name` VARCHAR(20) NULL COMMENT '姓名',
  `RegisterTime` DATETIME NOT NULL COMMENT '注册时间',
  `User` INT NOT NULL COMMENT '用户编号',
  PRIMARY KEY (`User`))
ENGINE = InnoDB
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `YuGiOh`.`BaseInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`BaseInfo` (
  `TypeId` INT NOT NULL,
  `TypeName` VARCHAR(64) NOT NULL,
  `ValueId` INT NOT NULL,
  `ValueName` VARCHAR(64) NOT NULL,
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YuGiOh`.`UserCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`UserCard` (
  `User` INT NOT NULL COMMENT '用户编号',
  `Name` VARCHAR(64) NOT NULL COMMENT '卡组名称',
  `Describe` VARCHAR(500) NULL COMMENT '卡组描述',
  `CreateTime` DATETIME NOT NULL COMMENT '创建时间',
  `UpdateTime` DATETIME NOT NULL COMMENT '更新时间',
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '卡组编号',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '用户卡组信息表';


-- -----------------------------------------------------
-- Table `YuGiOh`.`UserCardDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`UserCardDetail` (
  `Card` INT NOT NULL COMMENT '卡片编号',
  `Count` INT NOT NULL COMMENT '卡片数量',
  `UserCard` INT NOT NULL COMMENT '所属卡组',
  `Category` INT NOT NULL COMMENT '卡片位置（主卡组、副卡组、融合卡组）',
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '用户卡组卡片表';


-- -----------------------------------------------------
-- Table `YuGiOh`.`UserGameData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`UserGameData` (
  `User` INT NOT NULL COMMENT '用户编号',
  `Wins` INT NOT NULL COMMENT '胜场',
  `Losts` INT NOT NULL COMMENT '负场',
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '用户游戏信息表';


-- -----------------------------------------------------
-- Table `YuGiOh`.`GameRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YuGiOh`.`GameRecord` (
  `UserA` INT NOT NULL COMMENT '用户A编号',
  `UserB` INT NOT NULL COMMENT '用户B编号',
  `ARecord` TEXT NULL COMMENT '用户A操作记录',
  `BRecord` TEXT NULL COMMENT '用户B操作记录',
  `Winner` INT NOT NULL COMMENT '获胜者',
  `BeginTime` DATETIME NULL COMMENT '开始时间',
  `EndTime` DATETIME NULL COMMENT '结束时间',
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '游戏记录编号',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '游戏记录表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
